Repository vaguecoder/gorilla-mux, pull requests merged in 2023-01, with the labels that each got.

#5 Update issue templates
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/report-bug.md
Labels: enhancement

#18 Add First Workflow
  .github/workflows/test.yml
Labels: ci/cd

#27 Add CodeQL to Pipeline
  .github/workflows/codeQL.yml
Labels: ci/cd, feature

#29 Add `tests` Issue Template
  .github/ISSUE_TEMPLATE/tests.md
Labels: enhancement, misc, exclude-from-release

#34 Chore: Add .golangci.yaml file
  .golangci.yml
  Makefile
  doc.go
  example_authentication_middleware_test.go
  mux.go
  mux_test.go
  old_test.go
  regexp.go
  regexp_test.go
  route.go
Labels: golang, dev-exp, code-quality, todo
